/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.chungnh.simple.weather.view.custom;


import com.chungnh.simple.weather.data.model.ListDaily;
import com.chungnh.simple.weather.data.model.WMO;
import com.chungnh.simple.weather.utility.FormatUtil;
import com.chungnh.simple.weather.utility.DateTimeUtil;
import com.chungnh.simple.weather.utility.WMOCodeConverter;
import com.chungnh.simple.weather.utility.image.ImageLoader;

import javax.swing.*;

/**
 * @author chungnh
 */
public class DayOfWeekItemPane extends JPanel {

    /**
     * Creates new form HourlyWeatherItemPanel
     */
    public DayOfWeekItemPane(ListDaily.Item item, boolean showSeparator) {
        initComponents();
        txtDay.setText(DateTimeUtil.dayOfWeek(item.getTime()));
        WMO wmo = WMOCodeConverter.getInstance().decode(item.getWeatherCode());
        ImageLoader.loadSmIconWithShadow(wmo.getNight().getImageUrl(), txtWeather);
        txtWeather.setText(wmo.get(item.getTime()).getDescription());
        txtTemparature.setText(FormatUtil.temperature(item.getTemperatureMax(), item.getTemperatureMin()));
        jSeparator2.setVisible(showSeparator);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDay = new javax.swing.JLabel();
        txtWeather = new ImageView();
        txtTemparature = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(102, 204, 255));
        setOpaque(false);

        txtDay.setBackground(new java.awt.Color(255, 255, 255));
        txtDay.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtDay.setForeground(new java.awt.Color(147, 153, 162));
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDay.setText("Today");
        txtDay.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        txtDay.setPreferredSize(new java.awt.Dimension(100, 17));

        txtWeather.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtWeather.setText("Weather");

        txtTemparature.setForeground(new java.awt.Color(102, 102, 102));
        txtTemparature.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTemparature.setText("28℃");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWeather, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemparature, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeather)
                    .addComponent(txtTemparature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtDay;
    private javax.swing.JLabel txtTemparature;
    private javax.swing.JLabel txtWeather;
    // End of variables declaration//GEN-END:variables
}
