/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.chungnh.simple.weather.view.panel;

import com.chungnh.simple.weather.data.model.ListDaily;
import com.chungnh.simple.weather.view.custom.DayOfWeekItemPane;
import com.chungnh.simple.weather.view.custom.RoundedPanel;

import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * @author chungnh
 */
public class DailyWeatherPane extends RoundedPanel {

    /**
     * Creates new form WeekWeatherPane
     */
    public DailyWeatherPane() {
        initComponents();
        setBorder(new EmptyBorder(0, 20, 0, 20));
        pnlDaily.setLayout(new GridLayout(7, 0, 0, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaily = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 236, 239));

        pnlDaily.setBackground(new java.awt.Color(102, 204, 255));
        pnlDaily.setOpaque(false);
        pnlDaily.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("7-DAY FORECAST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaily, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlDaily;
    // End of variables declaration//GEN-END:variables

    public void setData(ListDaily listDaily) {
        pnlDaily.removeAll();
        for (int i = 0; i < listDaily.size(); i++) {
            ListDaily.Item item = listDaily.get(i);
            pnlDaily.add(new DayOfWeekItemPane(item, i < listDaily.size()-1));
        }
    }
}
